"""initial migration

Revision ID: e37eca62b450
Revises: 56e3c3c143bc
Create Date: 2025-05-13 15:31:11.549918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e37eca62b450'
down_revision: Union[str, None] = '56e3c3c143bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'rules',
               existing_type=postgresql.ENUM('no_smoking', 'pets_allowed', name='ruleschoices'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'rules',
               existing_type=postgresql.ENUM('no_smoking', 'pets_allowed', name='ruleschoices'),
               nullable=True)
    # ### end Alembic commands ###
